import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import topLogoImage from "../public/1106/top.svg";
import SbtIssue from "../pages/SbtIssue";
import style from "../styles/bgimage.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  const [account, setAccount] = useState<string>("");

  const connectWallet = () => {
    if (typeof globalThis.window?.ethereum !== "undefined") {
      window.ethereum
        .request({ method: "eth_requestAccounts" })
        .then((accounts) => {
          setAccount(accounts[0]);
        });
    } else {
      console.error("MetaMask is NOT installed. Please install it.");
    }
  };
  return (
    <div>
      <Head>
        <title>zkScore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-default_image h-screen w-screen  bg-cover">
        <div>
          {account !== "" ? (
            <SbtIssue account={account} />
          ) : (
            <div className="h-screen w-screen flex justify-center items-center">
              <Image
                src={topLogoImage}
                alt="logo"
                width={670}
                height={670}
                onClick={connectWallet}
                className="cursor-pointer"
              />
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
